site_name: Svelte Utility
site_url: https://svelte-u.netlify.app/
site_author: Mohamed Nesredin
site_description: A collection of utility functions, which help you build powerful
  app in svelte.
repo_name: svelte-u/docs
repo_url: https://github.com/svelte-u/docs
edit_uri: https://github.com/svelte-u/docs/tree/master/docs
copyright: Copyright &copy; 2022 Mohamed Nesredin
theme:
  name: material
  custom_dir: docs/overrides
  logo: https://avatars.githubusercontent.com/u/120715197
  icon:
    repo: fontawesome/brands/github-alt
  features:
  - navigation.tabs
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  - content.tabs.link
  - content.code.annotate
  - social
  font:
    text: Poppins
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    toggle:
      icon: material/weather-night
      name: Switch to light mode
plugins:
- search
- macros
- git-authors:
    show_contribution: true
    show_line_count: true
    count_empty_lines: true
- minify:
    minify_html: true
- git-revision-date-localized:
    type: timeago
nav:
- "Svelte Utility": 
  - Home: index.md
  - Contributing: contributing.md
- Actions:
  - "Drop Zone": "actions/dropzone.md"
  - "Element Bound": "actions/el_bound.md"
  - "Full Screen": "actions/fullscreen.md"
  - "Type Hint": "actions/type_hint.md"
- Browser:
  - "Active Element": "browser/active_el.md"
  - "breakpoints": "browser/breakpoints.md"
  - "Broadcast Channel": "browser/broadcast_channel.md"
  - "Clipboard": "browser/clipboard.md"
  - "dom_visible": "browser/dom_visible.md"
  - "Event Listener": "browser/event_listener.md"
  - "Eye Dropper": "browser/eye_dropper.md"
  - "Favicon": "browser/favicon.md"
  - "File Dialog": "browser/file_dialog.md"
  - "FPS": "browser/fps.md"
  - "GeoLocation": "browser/geolocation.md"
  - "Image": "browser/image.md"
  - "Intersection Observer": "browser/intersection_observer.md"
  - "Media Query": "browser/media_query.md"
  - "Memory": "browser/memory.md"
  - "Mouse": "browser/mouse.md"
  - "Mutation Observer": "browser/mutation_observer.md"
  - "Network": "browser/network.md"
  - "Notification": "browser/notification.md"
  - "Permission": "browser/permission.md"
  - "Preferred Language": "browser/preferred_lang.md"
  - "Push Notification": "browser/push_notification.md"
  - "Raf Fn": "browser/raf_fn.md"
  - "Resize Observer": "browser/resize_observer.md"
  - "Support": "browser/support.md"
  - "User Agent": "browser/useragent.md"
  - "Wake Lock": "browser/wake_lock.md"
  - "Websocket": "browser/websocket.md"
  - "Window Focus": "browser/window_focus.md"
  - "Window Scroll": "browser/window_scroll.md"
  - "Window Size": "browser/window_size.md"
  - "Worker": "browser/worker.md"
  - "Type Hint": "browser/type_hint.md"
- Extend:
  - "Async Validator": "extend/async_validator.md"
  - "Change Case": "extend/change_case.md"
  - "Firebase Cloud Messaging": "extend/fcm.md"
  - "Fuse": "extend/fuse.md"
  - "IDB KeyVal": "extend/idb_keyval.md"
  - "Jwt": "extend/jwt.md"
  - "Qr Code": "extend/qrcode.md"
- Shared:
  - "Adjust With Unit": "shared/adjust_with_unit.md"
  - "Async State": "shared/async_state.md"
  - "Create Event Hook": "shared/create_event_hook.md"
  - "Curry":
    - "Chain": "shared/curry/chain.md"
    - "Compose": "shared/curry/compose.md"
    - "Partial": "shared/curry/partial.md"
  - "Debounce": "shared/debounce.md"
  - "Dicts":
    - "Contains": "shared/dicts/contains.md"
    - "Enhance": "shared/dicts/enhance.md"
    - "Filter": "shared/dicts/filter.md"
    - "Invert": "shared/dicts/invert.md"
    - "Listify": "shared/dicts/listify.md"
    - "Picker": "shared/dicts/picker.md"
    - "Pops": "shared/dicts/pops.md"
  - "Interval Fn": "shared/intervalfn.md"
  - "IS": "shared/is.md"
  - "Last Change": "shared/last_changed.md"
  - "Len": "shared/len.md"
  - "Lists":
    - "Cluster": "shared/lists/cluster.md"
    - "Count": "shared/lists/count.md"
    - "Enhance": "shared/lists/enhance.md"
    - "Fork": "shared/lists/fork.md"
    - "Group": "shared/lists/group.md"
    - "Intersect": "shared/lists/intersects.md"
    - "Merge": "shared/lists/merge.md"
    - "Select": "shared/lists/select.md"
    - "Sort": "shared/lists/sort.md"
    - "Unique": "shared/lists/unique.md"
  - "Make Destructurable": "shared/make_destructurable.md"
  - "Object Url": "shared/object_url.md"
  - "Math":
    - "Arithmetic": "shared/math/arithmetic.md"
    - "Clamp": "shared/math/clamp.md"
    - "Precision": "shared/math/precision.md"
    - "Random": "shared/math/random.md"
  - "On Destroy": "shared/on_destroy.md"
  - "On Mount": "shared/on_mount.md"
  - "Range": "shared/range.md"
  - "Relative Time Format": "shared/rtf.md"
  - "Sleep": "shared/sleep.md"
  - "Slug": "shared/slug.md"
  - "Strftime": "shared/strftime.md"
  - "Taggable": "shared/taggable.md"
  - "Template": "shared/template.md"
  - "Throttle": "shared/throttle.md"
  - "Timeout": "shared/timeout.md"
  - "Timeout Fn": "shared/timeoutfn.md"
  - "To Number": "shared/to_number.md"
  - "To Readable": "shared/to_readable.md"
  - "To Writable": "shared/to_writable.md"
  - "Try it": "shared/tryit.md"
  - "Type": "shared/type.md"
  - "Unstore": "shared/unstore.md"
  - "Watchable": "shared/watchable.md"
  - "Type Hint": "shared/type_hint.md"
markdown_extensions:
- meta
- abbr
- tables
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.tabbed:
    alternate_style: true
- footnotes
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- attr_list
- def_list
- md_in_html
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js//mermaid.min.js
- js/termynal.js
- js/custom.js
- js/windicss.js

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/XM5uQhDHfZ
