site_name: Svelte Utility
site_url: https://svelte-u.netlify.app/
site_author: Mohamed Nesredin
site_description: A collection of utility functions, which help you build powerful
  app in svelte.
repo_name: svelte-u/docs
repo_url: https://github.com/svelte-u/docs
edit_uri: https://github.com/svelte-u/docs/tree/master/docs
copyright: Copyright &copy; 2022 Mohamed Nesredin
theme:
  name: material
  custom_dir: docs/overrides
  logo: https://avatars.githubusercontent.com/u/120715197
  icon:
    repo: fontawesome/brands/github-alt
  features:
  - navigation.tabs
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  - content.tabs.link
  - content.code.annotate
  - social
  font:
    text: Poppins
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    toggle:
      icon: material/weather-night
      name: Switch to light mode
plugins:
- search
- macros
- git-authors:
    show_contribution: true
    show_line_count: true
    count_empty_lines: true
- minify:
    minify_html: true
- git-revision-date-localized:
    type: timeago
nav:
- "Svelte Utility": 
  - Home: index.md
  - Contributing: contributing.md
# - Actions:
# - Browser:
# - Extend:
- Shared:
  - "Adjust With Unit": "shared/adjust_with_unit.md"
  - "Create Event Hook": "shared/create_event_hook.md"
  - "Curry":
    - "Chain": "shared/curry/chain.md"
    - "Compose": "shared/curry/compose.md"
  - "Debounce": "shared/debounce.md"
  - "Interval Fn": "shared/intervalfn.md"
  - "IS": "shared/is.md"
  - "Last Change": "shared/last_changed.md"
  - "Len": "shared/len.md"
  - "Make Destructurable": "shared/make_destructurable.md"
  - "On Destroy": "shared/on_destroy.md"
  - "On Mount": "shared/on_mount.md"
  - "Range": "shared/range.md"
  - "Relative Time Format": "shared/rtf.md"
  - "Sleep": "shared/sleep.md"
  - "Slug": "shared/slug.md"
  - "Strftime": "shared/strftime.md"
  - "Template": "shared/template.md"
  - "Throttle": "shared/throttle.md"
  - "Timeout": "shared/timeout.md"
  - "Timeout Fn": "shared/timeoutfn.md"
  - "To Number": "shared/to_number.md"
  - "To Readable": "shared/to_readable.md"
  - "To Writable": "shared/to_writable.md"
  - "Try it": "shared/tryit.md"
  - "Type": "shared/type.md"
  - "Unstore": "shared/unstore.md"
  - "Watchable": "shared/watchable.md"
markdown_extensions:
- meta
- abbr
- tables
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.tabbed:
    alternate_style: true
- footnotes
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- attr_list
- def_list
- md_in_html
- pymdownx.tasklist:
    custom_checkbox: true
    clickable_checkbox: true
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js//mermaid.min.js
- js/termynal.js
- js/custom.js
- js/windicss.js
